export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGIN_INITIATED = 'ADMIN_LOGIN_INITIATED';

export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOGOUT_FAILED = 'ADMIN_LOGOUT_FAILED';
export const ADMIN_LOGOUT_INITIATED = 'ADMIN_LOGOUT_INITIATED';

export const VOTER_LOGIN_SUCCESS = 'VOTER_LOGIN_SUCCESS';
export const VOTER_LOGIN_FAILED = 'VOTER_LOGIN_FAILED';
export const VOTER_LOGIN_INITIATED = 'VOTER_LOGIN_INITIATED';

export const VOTER_LOGOUT_SUCCESS = 'VOTER_LOGOUT_SUCCESS';
export const VOTER_LOGOUT_FAILED = 'VOTER_LOGOUT_FAILED';
export const VOTER_LOGOUT_INITIATED = 'VOTER_LOGOUT_INITIATED';

export const CANDIDATE_LOGOUT_SUCCESS = 'CANDIDATE_LOGOUT_SUCCESS';
export const CANDIDATE_LOGOUT_FAILED = 'CANDIDATE_LOGOUT_FAILED';
export const CANDIDATE_LOGOUT_INITIATED = 'CANDIDATE_LOGOUT_INITIATED';

export const VOTER_REGISTER_SUCCESS = 'VOTER_REGISTER_SUCCESS';
export const VOTER_REGISTER_FAILED = 'VOTER_REGISTER_FAILED';
export const VOTER_REGISTER_INITIATED = 'VOTER_REGISTER_INITIATED';

export const CANDIDATE_LOGIN_SUCCESS = 'CANDIDATE_LOGIN_SUCCESS';
export const CANDIDATE_LOGIN_FAILED = 'CANDIDATE_LOGIN_FAILED';
export const CANDIDATE_LOGIN_INITIATED = 'CANDIDATE_LOGIN_INITIATED';

export const CANDIDATE_REGISTER_SUCCESS = 'CANDIDATE_REGISTER_SUCCESS';
export const CANDIDATE_REGISTER_FAILED = 'CANDIDATE_REGISTER_FAILED';
export const CANDIDATE_REGISTER_INITIATED = 'CANDIDATE_REGISTER_INITIATED';

export const NOMINATE_CANDIDATE_SUCCESS = 'NOMINATE_CANDIDATE_SUCCESS';
export const LOAD_CANDIDATES_LIST_SUCCESS = 'LOAD_CANDIDATES_LIST_SUCCESS';
export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const VOTING_SUCCESS = 'VOTING_SUCCESS';

export const NOMINATE_CANDIDATE_FAILED = 'NOMINATE_CANDIDATE_FAILED';
export const LOAD_CANDIDATES_LIST_FAILED = 'LOAD_CANDIDATES_LIST_FAILED';
export const LOAD_RESULTS_FAILED = 'LOAD_RESULTS_FAILED';
export const VOTING_FAILED = 'VOTING_FAILED';